### ISSUE TITLE
Error posting to Facebook (No nonce in form submission! (0)

### ISSUE THREAD

**Issue by nitrokart** [mhaas/fbwlan#10]
Hi,

I'm trying to use your captive portal, however on the last step (../checkin?...) I always get this error.

Is there any way to fix it?
Thanks in advance

500 Internal Server Error

No nonce in form submission! (0)
#0 /var/www/fbwlan/include/flight/flight/core/Dispatcher.php(160): handle_checkin()
#1 /var/www/fbwlan/include/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction('handle_checkin', Array)
#2 /var/www/fbwlan/include/flight/flight/Engine.php(312): flight\core\Dispatcher::execute('handle_checkin', Array)
#3 /var/www/fbwlan/include/flight/flight/core/Dispatcher.php(191): flight\Engine->_start()
#4 /var/www/fbwlan/include/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 /var/www/fbwlan/include/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#6 /var/www/fbwlan/include/flight/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#7 /var/www/fbwlan/include/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#8 /var/www/fbwlan/include/flight/flight/core/Dispatcher.php(191): flight\Engine->start()
#9 /var/www/fbwlan/include/flight/flight/Flight.php(65): flight\core\Dispatcher::invokeMethod(Array, Array)
#10 /var/www/fbwlan/index.php(85): Flight::__callStatic('start', Array)
#11 /var/www/fbwlan/index.php(85): Flight::start()
#12 {main}

**Comment by mhaas** [comment]
Hey, thanks for the report. I had this fixed, but forgot to push the fix. Fixed in 57a9245.
