### ISSUE TITLE
Facebook DNS not Resolved on OpenWRT Chaos Calmer

### ISSUE THREAD

**Issue by agustindev** [mhaas/fbwlan#11]
Did you test the project on a box with OpenWRT 15.05 (Chaos Calmer)??

authsrv<-->internet<-->openwrtbox<-->apwifi<-->devicewifi

Steeps:
1) burn firmware OpenWRT 15.05 on Linksys E900
2) opkg install ipset
3) opkg install dnsmasq-full
4) opkg install wifidog
5) config wifidog authsrv (Amazon AWS VM)
6) finish running your scripts which appends init and hotplug files
everything works! wifi connect, redirect to AuthSrv, static CODE (gives internet connection), but when I try to connect with facebook check-out facebook dns are not resolved!

what would you do? try installing openwrt 14.07?

**Comment by mhaas** [comment]
You don't need the init and hotplug scripts anymore. The readme is outdated there. Wifidog now supports ipset natively: there is an example in wifidog.conf.

Did you also create the ipset beforehand and configure dnsmasq accordingly? Check the wifidog and dnsmasq logs.

Feel free to post all configs and logs if you keep having trouble.

**Comment by agustindev** [comment]
Thank you!
