### ISSUE TITLE
"FacebookRedirectLoginHelper.php" fatal error

### ISSUE THREAD

**Issue by xmflsct** [mhaas/fbwlan#29]
I am trying to set up a new gateway system on Raspberry Pi. My previous auth server stays unchanged. However after I set up wifidog, etc., I get the following error when I try to auth through Facebook. My previous gateway based on openwrt was working perfectly. I am not sure if this is an issue of my set up on Raspberry Pi, or the auth server? Auth through code is working fine.

`Fatal error: Cannot use object of type stdClass as array in /include/facebook-php-sdk-v4/src/Facebook/FacebookRedirectLoginHelper.php on line 192`

**Comment by mhaas** [comment]
I have recently started seeing the same error, but I haven't had time to investigate. Please let me know if you find a fix.

**Comment by mhaas** [comment]
Looks like a fix exists and we need to update the Facebook SDK. https://github.com/facebook/php-graph-sdk/pull/393

**Comment by mhaas** [comment]
@xmflsct Fixed. Make sure to update your checkout and your submodules! Let met know if this works.

**Comment by xmflsct** [comment]
@mhaas Thank you! It works great again!
